### ISSUE TITLE
Scale images to fit in overview table row

### ISSUE THREAD

**Issue by elarb** [flamelink/flamelink#10] opened 2018-01-13 13:38 UTC
An image is only partly shown if it doesn't fit in a row in the overview table.

**Comment by jperasmus** [comment] 2018-01-13 18:29
Thanks for reporting this. I've created a bugfix task for this in our backlog. Reference for it is: FBE-313

I'm going to close this task off here in the meantime since the issue is more related to the CMS itself than this JavaScript SDK repo. I see you also logged another issue via the Feedback modal within the CMS. Thanks for all the feedback 👍🏼

**Closed by jperasmus** 2018-01-13 18:29 UTC
